services:
  qingshu-server:
    image: vvnocode/qingshu-server:latest
    container_name: qingshu-server
    ports:
      - "52014:52014"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 256M

  # 使用MariaDB作为替代，低内存环境下更稳定
  db:
    container_name: mysql
    image: mariadb:10.11
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci', '--innodb_buffer_pool_size=40M', '--performance_schema=OFF' ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qingshu # 自动创建qingshu数据库
    volumes:
      - /appdata/mysql/mariadb/config:/etc/mysql/conf.d
      - /appdata/mysql/mariadb/data:/var/lib/mysql
    ports:
      - 16954:3306
    deploy:
      resources:
        limits:
          memory: 160M
