server:
  port: 52014

spring:
  application:
    name: qingshu-server
  
  # 数据源配置
  datasource:
    url: jdbc:mariadb://localhost:16954/qingshu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: pZlE5sP7s9Z9mJ
    driver-class-name: org.mariadb.jdbc.Driver
    
  # Jackson配置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰
    cache-enabled: false
  global-config:
    db-config:
      id-type: AUTO # 主键类型：数据库自增
      logic-delete-field: deleted # 逻辑删除字段
      logic-delete-value: 1 # 删除值
      logic-not-delete-value: 0 # 未删除值
  mapper-locations: classpath*:mapper/*.xml

# Swagger文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  
# 日志配置
logging:
  level:
    org.qingshu: info
    org.springframework.web: warn
